CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requester_id bigint                                  not null,
    created_at   timestamp without time zone default now(),
    primary key (id),
    foreign key (requester_id) references users (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(512)                            NOT NULL,
    is_available    BOOLEAN DEFAULT TRUE,
    owner_id        bigint                                  not null,
    item_request_id bigint,
    primary key (id),
    foreign key (owner_id) references users (id),
    foreign key (item_request_id) references item_requests (id)
);

create table if not exists bookings
(
    id        bigint generated by default as identity not null,
    start_at  timestamp without time zone             not null,
    end_at    timestamp without time zone             not null,
    item_id   bigint                                  not null,
    booker_id bigint                                  not null,
    status    varchar                                 not null,
    primary key (id),
    foreign key (item_id) references items (id),
    foreign key (booker_id) references users (id)
);

create table if not exists comments
(
    id         bigint generated by default as identity not null,
    text       varchar(255)                            not null,
    item_id    bigint                                  not null,
    author_id  bigint                                  not null,
    created_at timestamp without time zone default now(),
    primary key (id),
    foreign key (item_id) references items (id),
    foreign key (author_id) references users (id)
);